### ISSUE TITLE
Feature: Allow Users to Geo-Target Their URLs

### ISSUE THREAD

**Issue by Zingzy** [spoo-me/url-shortener#13]
## Description
Implement a feature that allows users to geo-target their URLs. This will enable users to redirect visitors to different URLs based on their geographic location, enhancing the relevance and effectiveness of their content.

## Tasks
- [ ] **Detect User Location**
    - Implement functionality to detect the geographic location of users based on their IP address.
    - Ensure accurate detection across a wide range of locations.

- [ ] **Store Geo-Targeted URLs**
    - Update the database schema to store URLs specific to different geographic locations.
    - Ensure backward compatibility with existing URLs.

- [ ] **Redirect Based on Location**
    - Implement logic to redirect users to the appropriate URL based on their geographic location.
    - Ensure the redirection is seamless and does not introduce significant latency.

- [ ] **User Interface Updates**
    - Update the URL creation and management interface to allow users to specify geo-targeted URLs.
    - Ensure the interface is user-friendly and intuitive.

- [ ] **Testing**
    - Write unit tests to verify the accuracy of location detection and redirection logic.
    - Perform integration tests to ensure the feature works seamlessly with the existing system.

- [ ] **Documentation**
    - Update the documentation to include details about the new geo-targeting feature.
    - Provide instructions on how to create and manage geo-targeted URLs.

**Comment by Zingzy** [comment]
Picking this up. Sharing the design that's going into the implementation, and the reasoning behind the main decisions.

**API shape: a flat country-to-URL map**

```jsonc
POST /api/v1/shorten
{
  "url": "https://example.com/global",
  "geo_rules": { "IN": "https://example.in/", "US": "https://example.com/us" }
}
```

Keys are ISO 3166-1 alpha-2 country codes, values are destination URLs. The main `url` always stays as the fallback for unmatched countries, so nothing breaks for existing links or clients. A map was chosen over a list of rule objects because duplicate countries become impossible by construction (JSON keys are unique), there is a single entry cap instead of two, and the stored shape is identical to the shape used for routing, so there is no transformation layer to get wrong.

**Country detection**

On spoo.me the visitor country comes from Cloudflare (the `CF-IPCountry` header), which is already computed at the edge and costs nothing per request. Self-hosted deployments without Cloudflare fall back to a local GeoLite2 lookup. Unknown or unresolvable countries always get the default destination. Detection only runs for links that actually have geo rules, so plain links pay zero overhead.

**Redirect flow**

The decision is a single dictionary lookup on the redirect hot path: `rules.get(country, default)`. Geo redirects are served with `Cache-Control: no-store` since the response varies per visitor. Analytics are unchanged; the country used for the routing decision is also recorded on the click event so stats and routing can never silently disagree.

**Edge cache support**

Hot links served from the Cloudflare Worker cache get a new `geo_redirect` entry type: the default URL plus the rules map in one KV entry. The Worker resolves the visitor country from `request.cf.country`, which is the same Cloudflare geodata the origin reads from the header, so an edge-served decision and an origin-served decision always agree. Older Worker versions treat the new entry type as unknown and pass through to origin, so deploy order does not matter.

**Safety**

Every per-country destination goes through the same validation as the main URL (scheme checks plus the blocklist), on both create and edit. The preview page (`spoo.me/abc+`) shows every destination of a geo-targeted link with a notice that it varies by country, so nobody can hide a destination from someone who inspects the link. Password-protected links keep hiding everything, as before.

**Limits and rollout**

Up to 50 country entries per link by default (self-hosters can override via config). Setting `geo_rules` requires authentication and is rolled out gradually behind a feature flag; clearing rules always works. API-only for now, with dashboard UI to follow.

**Comment by Zingzy** [comment]
Implementation is up in #230. Status against the task list:

- Location detection: done (Cloudflare header on spoo.me, GeoLite2 fallback for self-hosting)
- Schema + backward compatibility: done (`geo_rules` is a new optional field, existing links and cached entries are untouched, no migration needed)
- Redirect logic: done, including edge cache serving
- Testing: unit and integration coverage across validation, redirect paths, caching, and the Worker contract, plus local load testing (about 125k requests across both detection paths with zero wrong-country redirects, and a burst test showing the edge cache taking over mid-burst)
- UI: not in this PR, will come with the new dashboard
- Docs: pending, will follow once the API is live

**Comment by Zingzy** [comment]
Some diagrams for how the pieces fit together.

**1. Serving at the edge (Cloudflare Worker)**

```mermaid
flowchart TD
    V["Visitor request"] --> K{"Worker: KV entry for this code?"}
    K -- "no entry / excluded path" --> O["Passthrough to origin"]
    K -- "type: redirect" --> A["302 to the single destination"]
    K -- "type: geo_redirect" --> C{"visitor country in rules map?"}
    C -- "yes" --> B["302 to rules[country] with Cache-Control: no-store"]
    C -- "no / unknown country" --> D["302 to default url with Cache-Control: no-store"]
    K -- "unknown entry type / malformed" --> O
```

**2. Redirect flow at origin**

```mermaid
flowchart TD
    R["GET /abc at origin"] --> RES["Resolve link (Redis cache, then Mongo)"]
    RES --> PW{"password protected?"}
    PW -- "yes" --> PP["Password page"]
    PW -- "no" --> GR{"link has geo_rules?"}
    GR -- "no" --> BOT{"bot blocked?"}
    GR -- "yes" --> CC["Resolve country: CF-IPCountry header, else local GeoLite2 lookup"]
    CC --> PICK["destination = rules.get(country, default)"]
    PICK --> BOT
    BOT -- "yes" --> DENY["403"]
    BOT -- "no" --> EV["Emit click event (records the country used + whether a rule matched)"]
    EV --> RESP["302, plus no-store for geo links"]
```

**3. How a hot geo link reaches the edge cache**

```mermaid
sequenceDiagram
    participant U as Visitors
    participant O as Origin
    participant S as Redis Stream
    participant W as Click Worker
    participant KV as Edge KV
    participant E as Edge Worker
    U->>O: clicks on /abc
    O->>S: click events
    W->>S: consume events
    W->>W: hotness threshold crossed
    W->>KV: write geo_redirect entry (default + rules map)
    U->>E: subsequent clicks
    E->>KV: read entry
    E-->>U: 302 resolved per visitor country
```
